//
// MenuOutputDetailData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MenuOutputDetailData: Codable, JSONEncodable, Hashable {

    /** ID of the menu */
    public var id: String?
    /** The media (prompt) parameters */
    public var media: MenuOutputDetailMedia?
    /** A friendly name for the menu */
    public var name: String?
    /** The amount of time (in milliseconds) to wait for the caller to begin entering digits */
    public var timeout: Int?

    public init(id: String? = nil, media: MenuOutputDetailMedia? = nil, name: String? = nil, timeout: Int? = nil) {
        self.id = id
        self.media = media
        self.name = name
        self.timeout = timeout
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case media
        case name
        case timeout
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(media, forKey: .media)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(timeout, forKey: .timeout)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension MenuOutputDetailData: Identifiable {}
