//
// ModelFeatureDailySummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelFeatureDailySummary: Codable, JSONEncodable, Hashable {

    public var createdAt: String?
    public var featureCount: Int?
    public var featureName: String?
    public var logDate: String?

    public init(createdAt: String? = nil, featureCount: Int? = nil, featureName: String? = nil, logDate: String? = nil) {
        self.createdAt = createdAt
        self.featureCount = featureCount
        self.featureName = featureName
        self.logDate = logDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case featureCount = "feature_count"
        case featureName = "feature_name"
        case logDate = "log_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(featureCount, forKey: .featureCount)
        try container.encodeIfPresent(featureName, forKey: .featureName)
        try container.encodeIfPresent(logDate, forKey: .logDate)
    }
}

