//
// ModelEventDailySummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelEventDailySummary: Codable, JSONEncodable, Hashable {

    public var accountId: String?
    public var component: String?
    public var createdAt: String?
    public var transactionCount: Int?
    public var transactionDate: String?

    public init(accountId: String? = nil, component: String? = nil, createdAt: String? = nil, transactionCount: Int? = nil, transactionDate: String? = nil) {
        self.accountId = accountId
        self.component = component
        self.createdAt = createdAt
        self.transactionCount = transactionCount
        self.transactionDate = transactionDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId = "account_id"
        case component
        case createdAt = "created_at"
        case transactionCount = "transaction_count"
        case transactionDate = "transaction_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(component, forKey: .component)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(transactionCount, forKey: .transactionCount)
        try container.encodeIfPresent(transactionDate, forKey: .transactionDate)
    }
}

