//
// ModelsVOIPAccountMusicOnHold.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsVOIPAccountMusicOnHold: Codable, JSONEncodable, Hashable {

    public var mediaId: String?

    public init(mediaId: String? = nil) {
        self.mediaId = mediaId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mediaId = "media_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mediaId, forKey: .mediaId)
    }
}

