//
// ModelsCallForward.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsCallForward: Codable, JSONEncodable, Hashable {

    public static let numberRule = StringRule(minLength: nil, maxLength: 35, pattern: nil)
    public var enabled: Bool?
    public var number: String?

    public init(enabled: Bool? = nil, number: String? = nil) {
        self.enabled = enabled
        self.number = number
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case number
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(number, forKey: .number)
    }
}

