//
// ModelsTemplate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsTemplate: Codable, JSONEncodable, Hashable {

    public var brandName: String?
    public var createdAt: String?
    public var familyName: String?
    public var firmwareId: String?
    public var firmwareVersion: String?
    public var id: String?
    public var isActive: Bool?
    public var modelName: String?
    public var templateName: String?
    public var updatedAt: String?

    public init(brandName: String? = nil, createdAt: String? = nil, familyName: String? = nil, firmwareId: String? = nil, firmwareVersion: String? = nil, id: String? = nil, isActive: Bool? = nil, modelName: String? = nil, templateName: String? = nil, updatedAt: String? = nil) {
        self.brandName = brandName
        self.createdAt = createdAt
        self.familyName = familyName
        self.firmwareId = firmwareId
        self.firmwareVersion = firmwareVersion
        self.id = id
        self.isActive = isActive
        self.modelName = modelName
        self.templateName = templateName
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brandName = "brand_name"
        case createdAt = "created_at"
        case familyName = "family_name"
        case firmwareId = "firmware_id"
        case firmwareVersion = "firmware_version"
        case id
        case isActive = "is_active"
        case modelName = "model_name"
        case templateName = "template_name"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(brandName, forKey: .brandName)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(familyName, forKey: .familyName)
        try container.encodeIfPresent(firmwareId, forKey: .firmwareId)
        try container.encodeIfPresent(firmwareVersion, forKey: .firmwareVersion)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(modelName, forKey: .modelName)
        try container.encodeIfPresent(templateName, forKey: .templateName)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ModelsTemplate: Identifiable {}
