//
// ModelFeatureMonthlySummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelFeatureMonthlySummary: Codable, JSONEncodable, Hashable {

    public var createdAt: String?
    public var featureCount: Int?
    public var featureName: String?
    public var transactionMonth: Int?
    public var transactionYear: Int?

    public init(createdAt: String? = nil, featureCount: Int? = nil, featureName: String? = nil, transactionMonth: Int? = nil, transactionYear: Int? = nil) {
        self.createdAt = createdAt
        self.featureCount = featureCount
        self.featureName = featureName
        self.transactionMonth = transactionMonth
        self.transactionYear = transactionYear
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case featureCount = "feature_count"
        case featureName = "feature_name"
        case transactionMonth = "transaction_month"
        case transactionYear = "transaction_year"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(featureCount, forKey: .featureCount)
        try container.encodeIfPresent(featureName, forKey: .featureName)
        try container.encodeIfPresent(transactionMonth, forKey: .transactionMonth)
        try container.encodeIfPresent(transactionYear, forKey: .transactionYear)
    }
}

