//
// ModelCallMonthlySummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelCallMonthlySummary: Codable, JSONEncodable, Hashable {

    public var accountId: String?
    public var callMonth: Int?
    public var callType: String?
    public var callYear: Int?
    public var createdAt: String?
    public var totalCallDuration: String?

    public init(accountId: String? = nil, callMonth: Int? = nil, callType: String? = nil, callYear: Int? = nil, createdAt: String? = nil, totalCallDuration: String? = nil) {
        self.accountId = accountId
        self.callMonth = callMonth
        self.callType = callType
        self.callYear = callYear
        self.createdAt = createdAt
        self.totalCallDuration = totalCallDuration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId = "account_id"
        case callMonth = "call_month"
        case callType = "call_type"
        case callYear = "call_year"
        case createdAt = "created_at"
        case totalCallDuration = "total_call_duration"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(callMonth, forKey: .callMonth)
        try container.encodeIfPresent(callType, forKey: .callType)
        try container.encodeIfPresent(callYear, forKey: .callYear)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(totalCallDuration, forKey: .totalCallDuration)
    }
}

