//
// ServiceDocsPhonenumberUnassignPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceDocsPhonenumberUnassignPayload: Codable, JSONEncodable, Hashable {

    public var phonenumber: String?

    public init(phonenumber: String? = nil) {
        self.phonenumber = phonenumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phonenumber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phonenumber, forKey: .phonenumber)
    }
}

