//
// ServiceVOIPCallQueueRoleAssignData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceVOIPCallQueueRoleAssignData: Codable, JSONEncodable, Hashable {

    public enum Action: String, Codable, CaseIterable {
        case _set = "set"
    }
    public var action: Action
    public var recipients: [[String: [String]]]
    public var setMembership: Bool

    public init(action: Action, recipients: [[String: [String]]], setMembership: Bool) {
        self.action = action
        self.recipients = recipients
        self.setMembership = setMembership
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case recipients
        case setMembership = "set_membership"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(recipients, forKey: .recipients)
        try container.encode(setMembership, forKey: .setMembership)
    }
}

