//
// ServiceE911URIInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceE911URIInput: Codable, JSONEncodable, Hashable {

    public var callerName: String
    public var uri: String

    public init(callerName: String, uri: String) {
        self.callerName = callerName
        self.uri = uri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case callerName
        case uri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(callerName, forKey: .callerName)
        try container.encode(uri, forKey: .uri)
    }
}

