//
// ServiceRemoveURIApiOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceRemoveURIApiOutput: Codable, JSONEncodable, Hashable {

    public var uRIStatus: ServiceE911LocationURIStatus?

    public init(uRIStatus: ServiceE911LocationURIStatus? = nil) {
        self.uRIStatus = uRIStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uRIStatus = "URIStatus"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(uRIStatus, forKey: .uRIStatus)
    }
}

