//
// ServiceDeviceStatusOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceDeviceStatusOutput: Codable, JSONEncodable, Hashable {

    public var deviceId: String?
    public var registered: Bool?
    public var registrable: Bool?

    public init(deviceId: String? = nil, registered: Bool? = nil, registrable: Bool? = nil) {
        self.deviceId = deviceId
        self.registered = registered
        self.registrable = registrable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceId = "device_id"
        case registered
        case registrable
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(registered, forKey: .registered)
        try container.encodeIfPresent(registrable, forKey: .registrable)
    }
}

