//
// ServiceStoragePlan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceStoragePlan: Codable, JSONEncodable, Hashable {

    public var account: ServiceStoragePlanDatabase?
    public var aggregate: ServiceStoragePlanDatabase?
    public var modb: ServiceStoragePlanDatabase?
    public var system: ServiceStoragePlanDatabase?

    public init(account: ServiceStoragePlanDatabase? = nil, aggregate: ServiceStoragePlanDatabase? = nil, modb: ServiceStoragePlanDatabase? = nil, system: ServiceStoragePlanDatabase? = nil) {
        self.account = account
        self.aggregate = aggregate
        self.modb = modb
        self.system = system
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case aggregate
        case modb
        case system
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(aggregate, forKey: .aggregate)
        try container.encodeIfPresent(modb, forKey: .modb)
        try container.encodeIfPresent(system, forKey: .system)
    }
}

