//
// ServiceSystemStatusMessagingService.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceSystemStatusMessagingService: Codable, JSONEncodable, Hashable {

    public var messagingServer: String?

    public init(messagingServer: String? = nil) {
        self.messagingServer = messagingServer
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messagingServer = "messaging_server"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(messagingServer, forKey: .messagingServer)
    }
}

