//
// ServiceVOIPVoicemailMessageChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceVOIPVoicemailMessageChange: Codable, JSONEncodable, Hashable {

    public enum Folder: String, Codable, CaseIterable {
        case deleted = "deleted"
        case saved = "saved"
        case new = "new"
    }
    public var folder: Folder?
    public var sourceId: AnyCodable?

    public init(folder: Folder? = nil, sourceId: AnyCodable? = nil) {
        self.folder = folder
        self.sourceId = sourceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case folder
        case sourceId = "source_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encodeIfPresent(sourceId, forKey: .sourceId)
    }
}

