//
// ServiceWebhookEdit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceWebhookEdit: Codable, JSONEncodable, Hashable {

    public enum CallbackMethod: String, Codable, CaseIterable {
        case post = "POST"
        case put = "PUT"
    }
    public static let titleRule = StringRule(minLength: 3, maxLength: nil, pattern: nil)
    public var callbackMethod: CallbackMethod
    public var callbackUrl: String
    public var data: [String: AnyCodable]?
    public var isActive: Bool?
    public var title: String
    public var webhookType: String

    public init(callbackMethod: CallbackMethod, callbackUrl: String, data: [String: AnyCodable]? = nil, isActive: Bool? = nil, title: String, webhookType: String) {
        self.callbackMethod = callbackMethod
        self.callbackUrl = callbackUrl
        self.data = data
        self.isActive = isActive
        self.title = title
        self.webhookType = webhookType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case callbackMethod = "callback_method"
        case callbackUrl = "callback_url"
        case data
        case isActive = "is_active"
        case title
        case webhookType = "webhook_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(callbackMethod, forKey: .callbackMethod)
        try container.encode(callbackUrl, forKey: .callbackUrl)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encode(title, forKey: .title)
        try container.encode(webhookType, forKey: .webhookType)
    }
}

