//
// ServiceDocE911ActiveLocationOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceDocE911ActiveLocationOutput: Codable, JSONEncodable, Hashable {

    public var data: ServiceE911ActiveLocationOutput?
    /** Unique id for each request */
    public var requestId: String?
    /** HTTP response status code */
    public var statusCode: Int?

    public init(data: ServiceE911ActiveLocationOutput? = nil, requestId: String? = nil, statusCode: Int? = nil) {
        self.data = data
        self.requestId = requestId
        self.statusCode = statusCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case requestId = "request_id"
        case statusCode = "status_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
    }
}

