//
// ServiceE911LegacyDataOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceE911LegacyDataOutput: Codable, JSONEncodable, Hashable {

    public var houseNumber: String?
    public var predirectional: String?
    public var streetName: String?
    public var suite: String?

    public init(houseNumber: String? = nil, predirectional: String? = nil, streetName: String? = nil, suite: String? = nil) {
        self.houseNumber = houseNumber
        self.predirectional = predirectional
        self.streetName = streetName
        self.suite = suite
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case houseNumber = "house_number"
        case predirectional
        case streetName = "street_name"
        case suite
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(houseNumber, forKey: .houseNumber)
        try container.encodeIfPresent(predirectional, forKey: .predirectional)
        try container.encodeIfPresent(streetName, forKey: .streetName)
        try container.encodeIfPresent(suite, forKey: .suite)
    }
}

