//
// ServiceStorageOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceStorageOutput: Codable, JSONEncodable, Hashable {

    public var attachments: [String: AnyCodable]?
    public var connections: [String: AnyCodable]?
    public var id: String?
    public var plan: ServiceStoragePlan?

    public init(attachments: [String: AnyCodable]? = nil, connections: [String: AnyCodable]? = nil, id: String? = nil, plan: ServiceStoragePlan? = nil) {
        self.attachments = attachments
        self.connections = connections
        self.id = id
        self.plan = plan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attachments
        case connections
        case id
        case plan
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attachments, forKey: .attachments)
        try container.encodeIfPresent(connections, forKey: .connections)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(plan, forKey: .plan)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceStorageOutput: Identifiable {}
