//
// ServiceE911AddLocationInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceE911AddLocationInput: Codable, JSONEncodable, Hashable {

    public var location: ServiceE911LocationInput
    public var uri: ServiceE911URIInput

    public init(location: ServiceE911LocationInput, uri: ServiceE911URIInput) {
        self.location = location
        self.uri = uri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case location
        case uri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(location, forKey: .location)
        try container.encode(uri, forKey: .uri)
    }
}

