//
// ServiceVOIPChannelRunMetaflowData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceVOIPChannelRunMetaflowData: Codable, JSONEncodable, Hashable {

    public enum Module: String, Codable, CaseIterable {
        case transfer = "transfer"
        case hold = "hold"
    }
    public var children: [String: ServiceVOIPChannelRunMetaflowData]?
    public var data: [String: AnyCodable]?
    public var module: Module

    public init(children: [String: ServiceVOIPChannelRunMetaflowData]? = nil, data: [String: AnyCodable]? = nil, module: Module) {
        self.children = children
        self.data = data
        self.module = module
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case children
        case data
        case module
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(children, forKey: .children)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encode(module, forKey: .module)
    }
}

