//
// ServiceCampaignPhoneNumberOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceCampaignPhoneNumberOutput: Codable, JSONEncodable, Hashable {

    public var telephoneNumbers: [String]?
    public var totalCount: Int?

    public init(telephoneNumbers: [String]? = nil, totalCount: Int? = nil) {
        self.telephoneNumbers = telephoneNumbers
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case telephoneNumbers = "telephone_numbers"
        case totalCount = "total_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(telephoneNumbers, forKey: .telephoneNumbers)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
    }
}

