//
// ServiceAccountOutputShort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceAccountOutputShort: Codable, JSONEncodable, Hashable {

    public var descendantsCount: Int?
    public var flags: [String]?
    public var id: String?
    public var name: String?
    public var realm: String?

    public init(descendantsCount: Int? = nil, flags: [String]? = nil, id: String? = nil, name: String? = nil, realm: String? = nil) {
        self.descendantsCount = descendantsCount
        self.flags = flags
        self.id = id
        self.name = name
        self.realm = realm
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case descendantsCount = "descendants_count"
        case flags
        case id
        case name
        case realm
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(descendantsCount, forKey: .descendantsCount)
        try container.encodeIfPresent(flags, forKey: .flags)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(realm, forKey: .realm)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceAccountOutputShort: Identifiable {}
