//
// ServiceImpersonatedUserInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceImpersonatedUserInfo: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var firstName: String?
    public var fullName: String?
    public var hasAvatar: Bool?
    public var lastName: String?
    public var privLevel: String?

    public init(email: String? = nil, firstName: String? = nil, fullName: String? = nil, hasAvatar: Bool? = nil, lastName: String? = nil, privLevel: String? = nil) {
        self.email = email
        self.firstName = firstName
        self.fullName = fullName
        self.hasAvatar = hasAvatar
        self.lastName = lastName
        self.privLevel = privLevel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case firstName = "first_name"
        case fullName = "full_name"
        case hasAvatar = "has_avatar"
        case lastName = "last_name"
        case privLevel = "priv_level"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(hasAvatar, forKey: .hasAvatar)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(privLevel, forKey: .privLevel)
    }
}

