//
// ServiceVOIPQueueMembershipAddData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceVOIPQueueMembershipAddData: Codable, JSONEncodable, Hashable {

    public var recipientId: String

    public init(recipientId: String) {
        self.recipientId = recipientId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipientId = "recipient_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recipientId, forKey: .recipientId)
    }
}

