//
// ServicePhoneNumberResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServicePhoneNumberResult: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var phonenumber: String?
    public var status: String?

    public init(message: String? = nil, phonenumber: String? = nil, status: String? = nil) {
        self.message = message
        self.phonenumber = phonenumber
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case phonenumber
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(phonenumber, forKey: .phonenumber)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

