//
// ServiceVOIPDeviceAddEdit3d.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceVOIPDeviceAddEdit3d: Codable, JSONEncodable, Hashable {

    public var audio: ServiceVOIPDeviceAddEdit5?

    public init(audio: ServiceVOIPDeviceAddEdit5? = nil) {
        self.audio = audio
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audio
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(audio, forKey: .audio)
    }
}

