//
// ServiceVOIPDeviceAddEditProvision.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceVOIPDeviceAddEditProvision: Codable, JSONEncodable, Hashable {

    public var endpointBrand: String?
    public var endpointFamily: String?
    public var endpointModel: String?
    public var id: String?

    public init(endpointBrand: String? = nil, endpointFamily: String? = nil, endpointModel: String? = nil, id: String? = nil) {
        self.endpointBrand = endpointBrand
        self.endpointFamily = endpointFamily
        self.endpointModel = endpointModel
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointBrand = "endpoint_brand"
        case endpointFamily = "endpoint_family"
        case endpointModel = "endpoint_model"
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(endpointBrand, forKey: .endpointBrand)
        try container.encodeIfPresent(endpointFamily, forKey: .endpointFamily)
        try container.encodeIfPresent(endpointModel, forKey: .endpointModel)
        try container.encodeIfPresent(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceVOIPDeviceAddEditProvision: Identifiable {}
