//
// ServiceVOIPChannelRunActionData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceVOIPChannelRunActionData: Codable, JSONEncodable, Hashable {

    public var action: String
    public var moh: String?
    public var takebackDtmf: String?
    public var target: String?

    public init(action: String, moh: String? = nil, takebackDtmf: String? = nil, target: String? = nil) {
        self.action = action
        self.moh = moh
        self.takebackDtmf = takebackDtmf
        self.target = target
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case moh
        case takebackDtmf = "takeback_dtmf"
        case target
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encodeIfPresent(moh, forKey: .moh)
        try container.encodeIfPresent(takebackDtmf, forKey: .takebackDtmf)
        try container.encodeIfPresent(target, forKey: .target)
    }
}

