//
// ServiceE911ValidateLocationInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceE911ValidateLocationInput: Codable, JSONEncodable, Hashable {

    public var location: ServiceE911LocationInput

    public init(location: ServiceE911LocationInput) {
        self.location = location
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case location
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(location, forKey: .location)
    }
}

