//
// ServiceMetaflowOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceMetaflowOutput: Codable, JSONEncodable, Hashable {

    public var bindingDigit: String?
    public var numbers: [String: ServiceMetaflowPattern]?
    public var patterns: [String: ServiceMetaflowPattern]?

    public init(bindingDigit: String? = nil, numbers: [String: ServiceMetaflowPattern]? = nil, patterns: [String: ServiceMetaflowPattern]? = nil) {
        self.bindingDigit = bindingDigit
        self.numbers = numbers
        self.patterns = patterns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bindingDigit = "binding_digit"
        case numbers
        case patterns
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bindingDigit, forKey: .bindingDigit)
        try container.encodeIfPresent(numbers, forKey: .numbers)
        try container.encodeIfPresent(patterns, forKey: .patterns)
    }
}

