//
// ServiceE911ActiveLocationOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceE911ActiveLocationOutput: Codable, JSONEncodable, Hashable {

    public var locationStatus: ServiceE911ActiveLocationStatus?

    public init(locationStatus: ServiceE911ActiveLocationStatus? = nil) {
        self.locationStatus = locationStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locationStatus = "location_status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(locationStatus, forKey: .locationStatus)
    }
}

