//
// ServiceQueueRecipientOutputRecipient.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceQueueRecipientOutputRecipient: Codable, JSONEncodable, Hashable {

    public var features: ServiceQueueRecipientOutputRecipientFeatures?

    public init(features: ServiceQueueRecipientOutputRecipientFeatures? = nil) {
        self.features = features
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case features
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(features, forKey: .features)
    }
}

