//
// ServiceStoragePlanDatabaseDocument.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceStoragePlanDatabaseDocument: Codable, JSONEncodable, Hashable {

    public var attachments: ServiceStoragePlanDatabaseAttachment?
    public var connection: String?

    public init(attachments: ServiceStoragePlanDatabaseAttachment? = nil, connection: String? = nil) {
        self.attachments = attachments
        self.connection = connection
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attachments
        case connection
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attachments, forKey: .attachments)
        try container.encodeIfPresent(connection, forKey: .connection)
    }
}

