//
// ServiceTemporalRuleOutputFull.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceTemporalRuleOutputFull: Codable, JSONEncodable, Hashable {

    public var cycle: String?
    public var days: [Int]?
    public var enabled: Bool?
    public var id: String?
    public var interval: Int?
    public var month: Int?
    public var name: String?
    public var ordinal: String?
    public var startDate: Int?
    public var timeWindowStart: Int?
    public var timeWindowStop: Int?
    public var wdays: [String]?

    public init(cycle: String? = nil, days: [Int]? = nil, enabled: Bool? = nil, id: String? = nil, interval: Int? = nil, month: Int? = nil, name: String? = nil, ordinal: String? = nil, startDate: Int? = nil, timeWindowStart: Int? = nil, timeWindowStop: Int? = nil, wdays: [String]? = nil) {
        self.cycle = cycle
        self.days = days
        self.enabled = enabled
        self.id = id
        self.interval = interval
        self.month = month
        self.name = name
        self.ordinal = ordinal
        self.startDate = startDate
        self.timeWindowStart = timeWindowStart
        self.timeWindowStop = timeWindowStop
        self.wdays = wdays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cycle
        case days
        case enabled
        case id
        case interval
        case month
        case name
        case ordinal
        case startDate = "start_date"
        case timeWindowStart = "time_window_start"
        case timeWindowStop = "time_window_stop"
        case wdays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cycle, forKey: .cycle)
        try container.encodeIfPresent(days, forKey: .days)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(interval, forKey: .interval)
        try container.encodeIfPresent(month, forKey: .month)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(ordinal, forKey: .ordinal)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(timeWindowStart, forKey: .timeWindowStart)
        try container.encodeIfPresent(timeWindowStop, forKey: .timeWindowStop)
        try container.encodeIfPresent(wdays, forKey: .wdays)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceTemporalRuleOutputFull: Identifiable {}
