//
// ServiceVOIPDeviceAddEdit5.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceVOIPDeviceAddEdit5: Codable, JSONEncodable, Hashable {

    public var codecs: [String]?

    public init(codecs: [String]? = nil) {
        self.codecs = codecs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case codecs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(codecs, forKey: .codecs)
    }
}

