//
// ServiceTemporalRuleSetOutputShort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceTemporalRuleSetOutputShort: Codable, JSONEncodable, Hashable {

    public var features: [String]?
    public var flags: [String]?
    public var id: String?
    public var name: String?
    public var rules: [String]?

    public init(features: [String]? = nil, flags: [String]? = nil, id: String? = nil, name: String? = nil, rules: [String]? = nil) {
        self.features = features
        self.flags = flags
        self.id = id
        self.name = name
        self.rules = rules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case features
        case flags
        case id
        case name
        case rules
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(features, forKey: .features)
        try container.encodeIfPresent(flags, forKey: .flags)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(rules, forKey: .rules)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceTemporalRuleSetOutputShort: Identifiable {}
