//
// ServiceVOIPGroupAddEdit2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceVOIPGroupAddEdit2: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: 128, pattern: nil)
    public var endpoints: [String: ServiceEndpoint]
    public var name: String

    public init(endpoints: [String: ServiceEndpoint], name: String) {
        self.endpoints = endpoints
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpoints
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(endpoints, forKey: .endpoints)
        try container.encode(name, forKey: .name)
    }
}

