//
// ServiceAdminUserOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceAdminUserOutput: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var firstName: String?
    public var id: Int?
    public var lastName: String?

    public init(email: String? = nil, firstName: String? = nil, id: Int? = nil, lastName: String? = nil) {
        self.email = email
        self.firstName = firstName
        self.id = id
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case firstName = "first_name"
        case id
        case lastName = "last_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(lastName, forKey: .lastName)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceAdminUserOutput: Identifiable {}
