//
// ServiceGroupOutputShort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceGroupOutputShort: Codable, JSONEncodable, Hashable {

    public var endpoints: Int?
    public var features: [String]?
    public var flags: [String]?
    public var groupEndpoints: [String: ServiceEndpoint]?
    public var id: String?
    public var name: String?

    public init(endpoints: Int? = nil, features: [String]? = nil, flags: [String]? = nil, groupEndpoints: [String: ServiceEndpoint]? = nil, id: String? = nil, name: String? = nil) {
        self.endpoints = endpoints
        self.features = features
        self.flags = flags
        self.groupEndpoints = groupEndpoints
        self.id = id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpoints
        case features
        case flags
        case groupEndpoints = "group_endpoints"
        case id
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(endpoints, forKey: .endpoints)
        try container.encodeIfPresent(features, forKey: .features)
        try container.encodeIfPresent(flags, forKey: .flags)
        try container.encodeIfPresent(groupEndpoints, forKey: .groupEndpoints)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceGroupOutputShort: Identifiable {}
