//
// ServiceFeatureCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceFeatureCode: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: nil)
    public static let numberRule = StringRule(minLength: nil, maxLength: 30, pattern: nil)
    public var name: String?
    public var number: String?

    public init(name: String? = nil, number: String? = nil) {
        self.name = name
        self.number = number
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case number
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(number, forKey: .number)
    }
}

