//
// ServiceDocsPhonenumberAssignPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceDocsPhonenumberAssignPayload: Codable, JSONEncodable, Hashable {

    public var phonenumber: String?
    public var toAccount: String?

    public init(phonenumber: String? = nil, toAccount: String? = nil) {
        self.phonenumber = phonenumber
        self.toAccount = toAccount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phonenumber
        case toAccount = "to_account"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phonenumber, forKey: .phonenumber)
        try container.encodeIfPresent(toAccount, forKey: .toAccount)
    }
}

