//
// ServiceAPIResponseStatusCodeOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceAPIResponseStatusCodeOnly: Codable, JSONEncodable, Hashable {

    public var requestId: String?
    public var statusCode: Int?

    public init(requestId: String? = nil, statusCode: Int? = nil) {
        self.requestId = requestId
        self.statusCode = statusCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestId = "request_id"
        case statusCode = "status_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
    }
}

