//
// ServiceQueueRecipientOutputFull.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceQueueRecipientOutputFull: Codable, JSONEncodable, Hashable {

    public var displayName: String?
    public var id: String?
    public var name: String?
    public var recipient: ServiceQueueRecipientOutputFullRecipient?
    public var roles: [String: String]?

    public init(displayName: String? = nil, id: String? = nil, name: String? = nil, recipient: ServiceQueueRecipientOutputFullRecipient? = nil, roles: [String: String]? = nil) {
        self.displayName = displayName
        self.id = id
        self.name = name
        self.recipient = recipient
        self.roles = roles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case displayName = "display_name"
        case id
        case name
        case recipient
        case roles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(recipient, forKey: .recipient)
        try container.encodeIfPresent(roles, forKey: .roles)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceQueueRecipientOutputFull: Identifiable {}
