//
// ServiceCampaignImportOutputMnoStatusListInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceCampaignImportOutputMnoStatusListInner: Codable, JSONEncodable, Hashable {

    public var mnoId: String?
    public var mnoName: String?
    public var status: String?

    public init(mnoId: String? = nil, mnoName: String? = nil, status: String? = nil) {
        self.mnoId = mnoId
        self.mnoName = mnoName
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mnoId = "mno_id"
        case mnoName = "mno_name"
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mnoId, forKey: .mnoId)
        try container.encodeIfPresent(mnoName, forKey: .mnoName)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

