//
// ServiceCampaignTagDetagPhonenumbersOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceCampaignTagDetagPhonenumbersOutput: Codable, JSONEncodable, Hashable {

    public var orderId: String?
    public var orderStatus: String?

    public init(orderId: String? = nil, orderStatus: String? = nil) {
        self.orderId = orderId
        self.orderStatus = orderStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderId = "order_id"
        case orderStatus = "order_status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orderId, forKey: .orderId)
        try container.encodeIfPresent(orderStatus, forKey: .orderStatus)
    }
}

