//
// PhoneNumberAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PhoneNumberAPI {

    /**
     Get Assigned Numbers List
     
     - parameter accountid: (path) Account ID, 32 alpha numeric 
     - parameter startKey: (query) Start key for pagination, obtained from previous responses (optional)
     - parameter pageSize: (query) Number of records to return per page (range: 1 to 50) (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountidPhonenumberGet(accountid: String, startKey: String? = nil, pageSize: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsAccountPhonenumberGetAll?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountidPhonenumberGetWithRequestBuilder(accountid: accountid, startKey: startKey, pageSize: pageSize).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Assigned Numbers List
     - GET /v1/account/{accountid}/phonenumber
     - Access all phone numbers assigned to a CPaaS account.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountid: (path) Account ID, 32 alpha numeric 
     - parameter startKey: (query) Start key for pagination, obtained from previous responses (optional)
     - parameter pageSize: (query) Number of records to return per page (range: 1 to 50) (optional)
     - returns: RequestBuilder<ServiceDocsAccountPhonenumberGetAll> 
     */
    open class func v1AccountAccountidPhonenumberGetWithRequestBuilder(accountid: String, startKey: String? = nil, pageSize: Int? = nil) -> RequestBuilder<ServiceDocsAccountPhonenumberGetAll> {
        var localVariablePath = "/v1/account/{accountid}/phonenumber"
        let accountidPreEscape = "\(APIHelper.mapValueToPathItem(accountid))"
        let accountidPostEscape = accountidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountid}", with: accountidPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "start_key": (wrappedValue: startKey?.encodeToJSON(), isExplode: false),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: false),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsAccountPhonenumberGetAll>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Assign Number
     
     - parameter payload: (body) assignment payload 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountPhonenumberAssignPost(payload: ServiceDocsPhonenumberAssignPayload, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceAPIResponseStatusCodeOnly?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountPhonenumberAssignPostWithRequestBuilder(payload: payload).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Assign Number
     - POST /v1/account/phonenumber/assign
     - Assign a purchased phone number to an account.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter payload: (body) assignment payload 
     - returns: RequestBuilder<ServiceAPIResponseStatusCodeOnly> 
     */
    open class func v1AccountPhonenumberAssignPostWithRequestBuilder(payload: ServiceDocsPhonenumberAssignPayload) -> RequestBuilder<ServiceAPIResponseStatusCodeOnly> {
        let localVariablePath = "/v1/account/phonenumber/assign"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: payload)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceAPIResponseStatusCodeOnly>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Disconnect Number
     
     - parameter payload: (body) disconnect payload 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountPhonenumberDisconnectPost(payload: ServiceDocsPhonenumberUnassignPayload, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceAPIResponseStatusCodeOnly?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountPhonenumberDisconnectPostWithRequestBuilder(payload: payload).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Disconnect Number
     - POST /v1/account/phonenumber/disconnect
     - Disconnecting a phone number from a CPaaS account relinquishes ownership of the number back to the carrier.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter payload: (body) disconnect payload 
     - returns: RequestBuilder<ServiceAPIResponseStatusCodeOnly> 
     */
    open class func v1AccountPhonenumberDisconnectPostWithRequestBuilder(payload: ServiceDocsPhonenumberUnassignPayload) -> RequestBuilder<ServiceAPIResponseStatusCodeOnly> {
        let localVariablePath = "/v1/account/phonenumber/disconnect"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: payload)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceAPIResponseStatusCodeOnly>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Unassigned Numbers List
     
     - parameter startKey: (query) Start key for pagination, obtained from previous responses (optional)
     - parameter pageSize: (query) Number of records to return per page (range: 1 to 50) (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountPhonenumberGet(startKey: String? = nil, pageSize: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsAccountPhonenumberGetAll?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountPhonenumberGetWithRequestBuilder(startKey: startKey, pageSize: pageSize).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Unassigned Numbers List
     - GET /v1/account/phonenumber
     - Obtain all phone numbers that have not been assigned to a CPaaS account within your organization.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter startKey: (query) Start key for pagination, obtained from previous responses (optional)
     - parameter pageSize: (query) Number of records to return per page (range: 1 to 50) (optional)
     - returns: RequestBuilder<ServiceDocsAccountPhonenumberGetAll> 
     */
    open class func v1AccountPhonenumberGetWithRequestBuilder(startKey: String? = nil, pageSize: Int? = nil) -> RequestBuilder<ServiceDocsAccountPhonenumberGetAll> {
        let localVariablePath = "/v1/account/phonenumber"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "start_key": (wrappedValue: startKey?.encodeToJSON(), isExplode: false),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: false),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsAccountPhonenumberGetAll>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Purchase Number
     
     - parameter phonenumber: (body) phonenumber fields 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountPhonenumberPost(phonenumber: [String], apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsOrderPhonenumber?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountPhonenumberPostWithRequestBuilder(phonenumber: phonenumber).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Purchase Number
     - POST /v1/account/phonenumber
     - Purchase or activate a phone number for CPaaS accounts within your business.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter phonenumber: (body) phonenumber fields 
     - returns: RequestBuilder<ServiceDocsOrderPhonenumber> 
     */
    open class func v1AccountPhonenumberPostWithRequestBuilder(phonenumber: [String]) -> RequestBuilder<ServiceDocsOrderPhonenumber> {
        let localVariablePath = "/v1/account/phonenumber"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: phonenumber)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsOrderPhonenumber>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Unassign Number
     
     - parameter payload: (body) unassign payload 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountPhonenumberUnassignPost(payload: ServiceDocsPhonenumberUnassignPayload, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceAPIResponseStatusCodeOnly?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountPhonenumberUnassignPostWithRequestBuilder(payload: payload).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Unassign Number
     - POST /v1/account/phonenumber/unassign
     - Remove a phone number from an account and place it back on the list of unassigned phone numbers.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter payload: (body) unassign payload 
     - returns: RequestBuilder<ServiceAPIResponseStatusCodeOnly> 
     */
    open class func v1AccountPhonenumberUnassignPostWithRequestBuilder(payload: ServiceDocsPhonenumberUnassignPayload) -> RequestBuilder<ServiceAPIResponseStatusCodeOnly> {
        let localVariablePath = "/v1/account/phonenumber/unassign"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: payload)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceAPIResponseStatusCodeOnly>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search New Numbers
     
     - parameter areaCode: (query) Area code (exactly 3 numeric characters) example: 610 or 484 
     - parameter quantity: (query) Number of records to return (range: 1 to 100, defaults to 100 if not provided) (optional, default to 100)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1PhonenumberSearchGet(areaCode: String, quantity: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsPhonenumberSearchGetAll?, _ error: Error?) -> Void)) -> RequestTask {
        return v1PhonenumberSearchGetWithRequestBuilder(areaCode: areaCode, quantity: quantity).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search New Numbers
     - GET /v1/phonenumber/search
     - Conduct a search for available phone numbers for purchase within an area code.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter areaCode: (query) Area code (exactly 3 numeric characters) example: 610 or 484 
     - parameter quantity: (query) Number of records to return (range: 1 to 100, defaults to 100 if not provided) (optional, default to 100)
     - returns: RequestBuilder<ServiceDocsPhonenumberSearchGetAll> 
     */
    open class func v1PhonenumberSearchGetWithRequestBuilder(areaCode: String, quantity: Int? = nil) -> RequestBuilder<ServiceDocsPhonenumberSearchGetAll> {
        let localVariablePath = "/v1/phonenumber/search"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "area_code": (wrappedValue: areaCode.encodeToJSON(), isExplode: false),
            "quantity": (wrappedValue: quantity?.encodeToJSON(), isExplode: false),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsPhonenumberSearchGetAll>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
