//
// VoicemailAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class VoicemailAPI {

    /**
     Get Voicemail Box List
     
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter startKey: (query) start_key for pagination that was returned as next_start_key from your previous call (optional)
     - parameter pageSize: (query) number of records to return, range 1 to 50 (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailGet(accountID: String, startKey: String? = nil, pageSize: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsVoicemailGetAll?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailGetWithRequestBuilder(accountID: accountID, startKey: startKey, pageSize: pageSize).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Voicemail Box List
     - GET /v1/account/{accountID}/voicemail
     - List all voicemail boxes in an account.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter startKey: (query) start_key for pagination that was returned as next_start_key from your previous call (optional)
     - parameter pageSize: (query) number of records to return, range 1 to 50 (optional)
     - returns: RequestBuilder<ServiceDocsVoicemailGetAll> 
     */
    open class func v1AccountAccountIDVoicemailGetWithRequestBuilder(accountID: String, startKey: String? = nil, pageSize: Int? = nil) -> RequestBuilder<ServiceDocsVoicemailGetAll> {
        var localVariablePath = "/v1/account/{accountID}/voicemail"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "start_key": (wrappedValue: startKey?.encodeToJSON(), isExplode: false),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: false),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsVoicemailGetAll>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create Voicemail Box
     
     - parameter accountID: (path) account ID, 32 alphanumeric 
     - parameter voicemail: (body) voicemail payload fields 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailPost(accountID: String, voicemail: ServiceVOIPVoicemailAddEditData, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsVoicemailGetSingle?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailPostWithRequestBuilder(accountID: accountID, voicemail: voicemail).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Voicemail Box
     - POST /v1/account/{accountID}/voicemail
     - Create a voicemail box for receiving and storing voicemail messages.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) account ID, 32 alphanumeric 
     - parameter voicemail: (body) voicemail payload fields 
     - returns: RequestBuilder<ServiceDocsVoicemailGetSingle> 
     */
    open class func v1AccountAccountIDVoicemailPostWithRequestBuilder(accountID: String, voicemail: ServiceVOIPVoicemailAddEditData) -> RequestBuilder<ServiceDocsVoicemailGetSingle> {
        var localVariablePath = "/v1/account/{accountID}/voicemail"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: voicemail)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsVoicemailGetSingle>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Voicemail Box
     
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailVoicemailIDDelete(accountID: String, voicemailID: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsVoicemailGetSingle?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailVoicemailIDDeleteWithRequestBuilder(accountID: accountID, voicemailID: voicemailID).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Voicemail Box
     - DELETE /v1/account/{accountID}/voicemail/{voicemailID}
     - Delete a voicemail box in an account.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - returns: RequestBuilder<ServiceDocsVoicemailGetSingle> 
     */
    open class func v1AccountAccountIDVoicemailVoicemailIDDeleteWithRequestBuilder(accountID: String, voicemailID: String) -> RequestBuilder<ServiceDocsVoicemailGetSingle> {
        var localVariablePath = "/v1/account/{accountID}/voicemail/{voicemailID}"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let voicemailIDPreEscape = "\(APIHelper.mapValueToPathItem(voicemailID))"
        let voicemailIDPostEscape = voicemailIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voicemailID}", with: voicemailIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsVoicemailGetSingle>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Voicemail Box Details
     
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailVoicemailIDGet(accountID: String, voicemailID: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsVoicemailGetSingle?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailVoicemailIDGetWithRequestBuilder(accountID: accountID, voicemailID: voicemailID).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Voicemail Box Details
     - GET /v1/account/{accountID}/voicemail/{voicemailID}
     - Get information about a single voicemail box.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - returns: RequestBuilder<ServiceDocsVoicemailGetSingle> 
     */
    open class func v1AccountAccountIDVoicemailVoicemailIDGetWithRequestBuilder(accountID: String, voicemailID: String) -> RequestBuilder<ServiceDocsVoicemailGetSingle> {
        var localVariablePath = "/v1/account/{accountID}/voicemail/{voicemailID}"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let voicemailIDPreEscape = "\(APIHelper.mapValueToPathItem(voicemailID))"
        let voicemailIDPostEscape = voicemailIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voicemailID}", with: voicemailIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsVoicemailGetSingle>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Voicemail Message List
     
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) voicemail ID, 32 alpha numeric 
     - parameter startKey: (query) start_key for pagination that was returned as next_start_key from your previous call (optional)
     - parameter pageSize: (query) number of records to return, range 1 to 50 (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageGet(accountID: String, voicemailID: String, startKey: String? = nil, pageSize: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsVoicemailMessageGetAll?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailVoicemailIDMessageGetWithRequestBuilder(accountID: accountID, voicemailID: voicemailID, startKey: startKey, pageSize: pageSize).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Voicemail Message List
     - GET /v1/account/{accountID}/voicemail/{voicemailID}/message
     - Get a list of voicemail messages from an account's voicemail box.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) voicemail ID, 32 alpha numeric 
     - parameter startKey: (query) start_key for pagination that was returned as next_start_key from your previous call (optional)
     - parameter pageSize: (query) number of records to return, range 1 to 50 (optional)
     - returns: RequestBuilder<ServiceDocsVoicemailMessageGetAll> 
     */
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageGetWithRequestBuilder(accountID: String, voicemailID: String, startKey: String? = nil, pageSize: Int? = nil) -> RequestBuilder<ServiceDocsVoicemailMessageGetAll> {
        var localVariablePath = "/v1/account/{accountID}/voicemail/{voicemailID}/message"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let voicemailIDPreEscape = "\(APIHelper.mapValueToPathItem(voicemailID))"
        let voicemailIDPostEscape = voicemailIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voicemailID}", with: voicemailIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "start_key": (wrappedValue: startKey?.encodeToJSON(), isExplode: false),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: false),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsVoicemailMessageGetAll>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Voicemail Message
     
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - parameter messageID: (path) message ID, 32 alpha numeric 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDDelete(accountID: String, voicemailID: String, messageID: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsVoicemailMessageGetSingle?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDDeleteWithRequestBuilder(accountID: accountID, voicemailID: voicemailID, messageID: messageID).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Voicemail Message
     - DELETE /v1/account/{accountID}/voicemail/{voicemailID}/message/{messageID}
     - Delete a voicemail message from a voicemail box in an account.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - parameter messageID: (path) message ID, 32 alpha numeric 
     - returns: RequestBuilder<ServiceDocsVoicemailMessageGetSingle> 
     */
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDDeleteWithRequestBuilder(accountID: String, voicemailID: String, messageID: String) -> RequestBuilder<ServiceDocsVoicemailMessageGetSingle> {
        var localVariablePath = "/v1/account/{accountID}/voicemail/{voicemailID}/message/{messageID}"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let voicemailIDPreEscape = "\(APIHelper.mapValueToPathItem(voicemailID))"
        let voicemailIDPostEscape = voicemailIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voicemailID}", with: voicemailIDPostEscape, options: .literal, range: nil)
        let messageIDPreEscape = "\(APIHelper.mapValueToPathItem(messageID))"
        let messageIDPostEscape = messageIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{messageID}", with: messageIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsVoicemailMessageGetSingle>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Voicemail Message Details
     
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - parameter messageID: (path) Message ID, 39 (yyyymm-&lt;32 id&gt;) 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDGet(accountID: String, voicemailID: String, messageID: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsVoicemailMessageGetSingle?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDGetWithRequestBuilder(accountID: accountID, voicemailID: voicemailID, messageID: messageID).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Voicemail Message Details
     - GET /v1/account/{accountID}/voicemail/{voicemailID}/message/{messageID}
     - Retrieve the container details of an individual voicemail message. This includes a reference to the audio file, but not the message itself.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - parameter messageID: (path) Message ID, 39 (yyyymm-&lt;32 id&gt;) 
     - returns: RequestBuilder<ServiceDocsVoicemailMessageGetSingle> 
     */
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDGetWithRequestBuilder(accountID: String, voicemailID: String, messageID: String) -> RequestBuilder<ServiceDocsVoicemailMessageGetSingle> {
        var localVariablePath = "/v1/account/{accountID}/voicemail/{voicemailID}/message/{messageID}"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let voicemailIDPreEscape = "\(APIHelper.mapValueToPathItem(voicemailID))"
        let voicemailIDPostEscape = voicemailIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voicemailID}", with: voicemailIDPostEscape, options: .literal, range: nil)
        let messageIDPreEscape = "\(APIHelper.mapValueToPathItem(messageID))"
        let messageIDPostEscape = messageIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{messageID}", with: messageIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsVoicemailMessageGetSingle>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Voicemail Message
     
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - parameter messageID: (path) Message ID, 39 (yyyymm-&lt;32 id&gt;) 
     - parameter reqBody: (body) payload fields 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDPut(accountID: String, voicemailID: String, messageID: String, reqBody: ServiceVOIPVoicemailMessageChange, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsVoicemailMessageGetSingle?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDPutWithRequestBuilder(accountID: accountID, voicemailID: voicemailID, messageID: messageID, reqBody: reqBody).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Voicemail Message
     - PUT /v1/account/{accountID}/voicemail/{voicemailID}/message/{messageID}
     - Copy or move a voicemail message to a different folder in the same voicemail box or move the message to a separate voicemail box.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - parameter messageID: (path) Message ID, 39 (yyyymm-&lt;32 id&gt;) 
     - parameter reqBody: (body) payload fields 
     - returns: RequestBuilder<ServiceDocsVoicemailMessageGetSingle> 
     */
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDPutWithRequestBuilder(accountID: String, voicemailID: String, messageID: String, reqBody: ServiceVOIPVoicemailMessageChange) -> RequestBuilder<ServiceDocsVoicemailMessageGetSingle> {
        var localVariablePath = "/v1/account/{accountID}/voicemail/{voicemailID}/message/{messageID}"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let voicemailIDPreEscape = "\(APIHelper.mapValueToPathItem(voicemailID))"
        let voicemailIDPostEscape = voicemailIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voicemailID}", with: voicemailIDPostEscape, options: .literal, range: nil)
        let messageIDPreEscape = "\(APIHelper.mapValueToPathItem(messageID))"
        let messageIDPostEscape = messageIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{messageID}", with: messageIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: reqBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsVoicemailMessageGetSingle>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Voicemail Message File
     
     - parameter accountID: (path) Account ID, unique 32-character alphanumeric identifier 
     - parameter voicemailID: (path) Voicemail Box ID, unique 32-character alphanumeric identifier 
     - parameter messageID: (path) Message ID, unique 32-character alphanumeric identifier 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDRawGet(accountID: String, voicemailID: String, messageID: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: URL?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDRawGetWithRequestBuilder(accountID: accountID, voicemailID: voicemailID, messageID: messageID).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Voicemail Message File
     - GET /v1/account/{accountID}/voicemail/{voicemailID}/message/{messageID}/raw
     - Get the original audio content of a specific voicemail message identified by its unique ID within an account's voicemail box. URL Param \"voicemailID\" is a unique 32-character alphanumeric identifier assigned by the system, which refers to a specific voicemail box. URL Param \"messageID\" is a unique 32-character alphanumeric identifier assigned by the system, which refers to a specific message within a voicemail box.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) Account ID, unique 32-character alphanumeric identifier 
     - parameter voicemailID: (path) Voicemail Box ID, unique 32-character alphanumeric identifier 
     - parameter messageID: (path) Message ID, unique 32-character alphanumeric identifier 
     - returns: RequestBuilder<URL> 
     */
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDRawGetWithRequestBuilder(accountID: String, voicemailID: String, messageID: String) -> RequestBuilder<URL> {
        var localVariablePath = "/v1/account/{accountID}/voicemail/{voicemailID}/message/{messageID}/raw"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let voicemailIDPreEscape = "\(APIHelper.mapValueToPathItem(voicemailID))"
        let voicemailIDPostEscape = voicemailIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voicemailID}", with: voicemailIDPostEscape, options: .literal, range: nil)
        let messageIDPreEscape = "\(APIHelper.mapValueToPathItem(messageID))"
        let messageIDPostEscape = messageIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{messageID}", with: messageIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Add Voicemail Message File
     
     - parameter accountID: (path) Account ID, 32 alphanumeric characters 
     - parameter voicemailID: (path) Voicemail ID, 32 alphanumeric characters 
     - parameter messageID: (path) Message ID, 32 alphanumeric characters 
     - parameter file: (form) Audio file to upload 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDRawPost(accountID: String, voicemailID: String, messageID: String, file: URL, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [String: AnyCodable]?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDRawPostWithRequestBuilder(accountID: accountID, voicemailID: voicemailID, messageID: messageID, file: file).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add Voicemail Message File
     - POST /v1/account/{accountID}/voicemail/{voicemailID}/message/{messageID}/raw
     - Associate an audio recording file with the voicemail to fully complete the message.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) Account ID, 32 alphanumeric characters 
     - parameter voicemailID: (path) Voicemail ID, 32 alphanumeric characters 
     - parameter messageID: (path) Message ID, 32 alphanumeric characters 
     - parameter file: (form) Audio file to upload 
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func v1AccountAccountIDVoicemailVoicemailIDMessageMessageIDRawPostWithRequestBuilder(accountID: String, voicemailID: String, messageID: String, file: URL) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/account/{accountID}/voicemail/{voicemailID}/message/{messageID}/raw"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let voicemailIDPreEscape = "\(APIHelper.mapValueToPathItem(voicemailID))"
        let voicemailIDPostEscape = voicemailIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voicemailID}", with: voicemailIDPostEscape, options: .literal, range: nil)
        let messageIDPreEscape = "\(APIHelper.mapValueToPathItem(messageID))"
        let messageIDPostEscape = messageIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{messageID}", with: messageIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "file": file.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create Voicemail Message
     
     - parameter accountID: (path) account ID, 32 alphanumeric 
     - parameter voicemailID: (path) voicemail ID, 32 alphanumeric 
     - parameter message: (body) voicemail message payload fields 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailVoicemailIDMessagePost(accountID: String, voicemailID: String, message: ServiceVOIPVoicemailMessageAddData, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsVoicemailMessageGetSingle?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailVoicemailIDMessagePostWithRequestBuilder(accountID: accountID, voicemailID: voicemailID, message: message).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Voicemail Message
     - POST /v1/account/{accountID}/voicemail/{voicemailID}/message
     - Create the container information for a recorded voicemail message in a voicemail box.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) account ID, 32 alphanumeric 
     - parameter voicemailID: (path) voicemail ID, 32 alphanumeric 
     - parameter message: (body) voicemail message payload fields 
     - returns: RequestBuilder<ServiceDocsVoicemailMessageGetSingle> 
     */
    open class func v1AccountAccountIDVoicemailVoicemailIDMessagePostWithRequestBuilder(accountID: String, voicemailID: String, message: ServiceVOIPVoicemailMessageAddData) -> RequestBuilder<ServiceDocsVoicemailMessageGetSingle> {
        var localVariablePath = "/v1/account/{accountID}/voicemail/{voicemailID}/message"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let voicemailIDPreEscape = "\(APIHelper.mapValueToPathItem(voicemailID))"
        let voicemailIDPostEscape = voicemailIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voicemailID}", with: voicemailIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: message)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsVoicemailMessageGetSingle>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Voicemail Box
     
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - parameter reqBody: (body) payload fields 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func v1AccountAccountIDVoicemailVoicemailIDPut(accountID: String, voicemailID: String, reqBody: ServiceVOIPVoicemailAddEditData, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServiceDocsVoicemailGetSingle?, _ error: Error?) -> Void)) -> RequestTask {
        return v1AccountAccountIDVoicemailVoicemailIDPutWithRequestBuilder(accountID: accountID, voicemailID: voicemailID, reqBody: reqBody).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Voicemail Box
     - PUT /v1/account/{accountID}/voicemail/{voicemailID}
     - Update the settings in an individual voicemail box, such as the owner, PIN, etc.
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: BearerAuth
     - parameter accountID: (path) Account ID, 32 alpha numeric 
     - parameter voicemailID: (path) Voicemail ID, 32 alpha numeric 
     - parameter reqBody: (body) payload fields 
     - returns: RequestBuilder<ServiceDocsVoicemailGetSingle> 
     */
    open class func v1AccountAccountIDVoicemailVoicemailIDPutWithRequestBuilder(accountID: String, voicemailID: String, reqBody: ServiceVOIPVoicemailAddEditData) -> RequestBuilder<ServiceDocsVoicemailGetSingle> {
        var localVariablePath = "/v1/account/{accountID}/voicemail/{voicemailID}"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let voicemailIDPreEscape = "\(APIHelper.mapValueToPathItem(voicemailID))"
        let voicemailIDPostEscape = voicemailIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voicemailID}", with: voicemailIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: reqBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceDocsVoicemailGetSingle>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
